package com.github.warrentode.todecoins.datagen.tags;

import com.github.warrentode.todecoins.util.tags.ForgeTags;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.tags.BiomeTagsProvider;
import net.minecraft.world.level.biome.Biomes;
import net.minecraftforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

public class BiomeTagsGen extends BiomeTagsProvider {
    public BiomeTagsGen(DataGenerator generator, String modid, @Nullable ExistingFileHelper helper) {
        super(generator, modid, helper);
    }

    @Override
    protected void addTags() {
        registerTags();
    }

    private void registerTags() {
        tag(ForgeTags.Biomes.HAS_SUNFLOWER)
                .add(Biomes.SUNFLOWER_PLAINS)
                .add(Biomes.ICE_SPIKES);
        tag(ForgeTags.Biomes.HAS_PEONY)
                .add(Biomes.OLD_GROWTH_BIRCH_FOREST)
                .add(Biomes.FOREST)
                .add(Biomes.DARK_FOREST)
                .add(Biomes.FLOWER_FOREST)
                .add(Biomes.BIRCH_FOREST);
        tag(ForgeTags.Biomes.HAS_ROSE_BUSH)
                .add(Biomes.OLD_GROWTH_BIRCH_FOREST)
                .add(Biomes.FOREST)
                .add(Biomes.DARK_FOREST)
                .add(Biomes.FLOWER_FOREST)
                .add(Biomes.BIRCH_FOREST);
        tag(ForgeTags.Biomes.HAS_LILAC)
                .add(Biomes.OLD_GROWTH_BIRCH_FOREST)
                .add(Biomes.FOREST)
                .add(Biomes.DARK_FOREST)
                .add(Biomes.FLOWER_FOREST)
                .add(Biomes.BIRCH_FOREST);
        tag(ForgeTags.Biomes.HAS_BUTTERCUP)
                .add(Biomes.FLOWER_FOREST)
                .add(Biomes.MEADOW)
                .add(Biomes.SUNFLOWER_PLAINS);
        tag(ForgeTags.Biomes.HAS_LILY_OF_THE_VALLEY)
                .add(Biomes.OLD_GROWTH_BIRCH_FOREST)
                .add(Biomes.FOREST)
                .add(Biomes.DARK_FOREST)
                .add(Biomes.FLOWER_FOREST)
                .add(Biomes.BIRCH_FOREST);
        tag(ForgeTags.Biomes.HAS_CORNFLOWER)
                .add(Biomes.DRIPSTONE_CAVES)
                .add(Biomes.DEEP_DARK)
                .add(Biomes.PLAINS)
                .add(Biomes.SUNFLOWER_PLAINS)
                .add(Biomes.MEADOW);
        tag(ForgeTags.Biomes.HAS_OXEYE_DAISY)
                .add(Biomes.DRIPSTONE_CAVES)
                .add(Biomes.DEEP_DARK)
                .add(Biomes.PLAINS)
                .add(Biomes.SUNFLOWER_PLAINS)
                .add(Biomes.MEADOW);
        tag(ForgeTags.Biomes.HAS_PINK_TULIP)
                .add(Biomes.DRIPSTONE_CAVES)
                .add(Biomes.DEEP_DARK)
                .add(Biomes.PLAINS)
                .add(Biomes.SUNFLOWER_PLAINS)
                .add(Biomes.MEADOW);
        tag(ForgeTags.Biomes.HAS_WHITE_TULIP)
                .add(Biomes.DRIPSTONE_CAVES)
                .add(Biomes.DEEP_DARK)
                .add(Biomes.PLAINS)
                .add(Biomes.SUNFLOWER_PLAINS)
                .add(Biomes.MEADOW);
        tag(ForgeTags.Biomes.HAS_ORANGE_TULIP)
                .add(Biomes.DRIPSTONE_CAVES)
                .add(Biomes.DEEP_DARK)
                .add(Biomes.PLAINS)
                .add(Biomes.SUNFLOWER_PLAINS)
                .add(Biomes.MEADOW);
        tag(ForgeTags.Biomes.HAS_RED_TULIP)
                .add(Biomes.DRIPSTONE_CAVES)
                .add(Biomes.DEEP_DARK)
                .add(Biomes.PLAINS)
                .add(Biomes.SUNFLOWER_PLAINS)
                .add(Biomes.MEADOW);
        tag(ForgeTags.Biomes.HAS_RED_TULIP)
                .add(Biomes.FLOWER_FOREST)
                .add(Biomes.DRIPSTONE_CAVES)
                .add(Biomes.DEEP_DARK)
                .add(Biomes.PLAINS)
                .add(Biomes.SUNFLOWER_PLAINS)
                .add(Biomes.MEADOW);
        tag(ForgeTags.Biomes.HAS_ALLIUM)
                .add(Biomes.FLOWER_FOREST)
                .add(Biomes.MEADOW);
        tag(ForgeTags.Biomes.HAS_BLUE_ORCHID)
                .add(Biomes.SWAMP);
        tag(ForgeTags.Biomes.HAS_DARK_OAK)
                .add(Biomes.DARK_FOREST);
        tag(ForgeTags.Biomes.HAS_BIRCH)
                .add(Biomes.OLD_GROWTH_BIRCH_FOREST)
                .add(Biomes.BIRCH_FOREST)
                .add(Biomes.FLOWER_FOREST)
                .add(Biomes.FOREST);
        tag(ForgeTags.Biomes.HAS_JUNGLE)
                .add(Biomes.SPARSE_JUNGLE)
                .add(Biomes.BAMBOO_JUNGLE)
                .add(Biomes.JUNGLE);
        tag(ForgeTags.Biomes.HAS_ACACIA)
                .add(Biomes.WINDSWEPT_SAVANNA)
                .add(Biomes.SAVANNA_PLATEAU)
                .add(Biomes.SAVANNA);
        tag(ForgeTags.Biomes.HAS_MANGROVE)
                .add(Biomes.MANGROVE_SWAMP);
        tag(ForgeTags.Biomes.HAS_SPRUCE)
                .add(Biomes.TAIGA)
                .add(Biomes.FROZEN_RIVER)
                .add(Biomes.SNOWY_BEACH)
                .add(Biomes.FROZEN_PEAKS)
                .add(Biomes.GROVE)
                .add(Biomes.SNOWY_PLAINS)
                .add(Biomes.ICE_SPIKES)
                .add(Biomes.JAGGED_PEAKS)
                .add(Biomes.SNOWY_SLOPES)
                .add(Biomes.SNOWY_TAIGA)
                .add(Biomes.WINDSWEPT_HILLS)
                .add(Biomes.WINDSWEPT_GRAVELLY_HILLS)
                .add(Biomes.WINDSWEPT_FOREST)
                .add(Biomes.OLD_GROWTH_SPRUCE_TAIGA)
                .add(Biomes.OLD_GROWTH_PINE_TAIGA);
        tag(ForgeTags.Biomes.NETHER_BIOMES)
                .add(Biomes.BASALT_DELTAS)
                .add(Biomes.NETHER_WASTES)
                .add(Biomes.WARPED_FOREST)
                .add(Biomes.CRIMSON_FOREST)
                .add(Biomes.SOUL_SAND_VALLEY);
        tag(ForgeTags.Biomes.HAS_WARPED_FUNGUS)
                .add(Biomes.WARPED_FOREST);
        tag(ForgeTags.Biomes.HAS_CRIMSON_FUNGUS)
                .add(Biomes.CRIMSON_FOREST);
        tag(ForgeTags.Biomes.HAS_SANDSTONE)
                .add(Biomes.SNOWY_BEACH)
                .add(Biomes.BEACH)
                .add(Biomes.DESERT);
        tag(ForgeTags.Biomes.HAS_RED_SANDSTONE)
                .add(Biomes.WOODED_BADLANDS)
                .add(Biomes.ERODED_BADLANDS)
                .add(Biomes.BADLANDS);
        tag(ForgeTags.Biomes.HAS_MOSSY_STONE)
                .add(Biomes.TAIGA)
                .add(Biomes.OLD_GROWTH_PINE_TAIGA)
                .add(Biomes.OLD_GROWTH_SPRUCE_TAIGA);
        tag(ForgeTags.Biomes.HAS_PUFFERFISH)
                .add(Biomes.LUKEWARM_OCEAN)
                .add(Biomes.DEEP_LUKEWARM_OCEAN)
                .add(Biomes.WARM_OCEAN);
        tag(ForgeTags.Biomes.HAS_TROPICAL_FISH)
                .add(Biomes.LUSH_CAVES)
                .add(Biomes.MANGROVE_SWAMP)
                .add(Biomes.LUKEWARM_OCEAN)
                .add(Biomes.DEEP_LUKEWARM_OCEAN)
                .add(Biomes.WARM_OCEAN);
        tag(ForgeTags.Biomes.HAS_SALMON)
                .add(Biomes.RIVER)
                .add(Biomes.FROZEN_RIVER)
                .add(Biomes.COLD_OCEAN)
                .add(Biomes.DEEP_COLD_OCEAN)
                .add(Biomes.FROZEN_OCEAN)
                .add(Biomes.DEEP_FROZEN_OCEAN);
        tag(ForgeTags.Biomes.HAS_FROGS)
                .add(Biomes.SWAMP)
                .add(Biomes.MANGROVE_SWAMP);
        tag(ForgeTags.Biomes.HAS_AXOLOTL)
                .add(Biomes.LUSH_CAVES);
        tag(ForgeTags.Biomes.HAS_MUD)
                .add(Biomes.MANGROVE_SWAMP);
    }
}