package com.github.warrentode.todecoins.entity.villager.trades;

import com.github.warrentode.todecoins.entity.villager.trades.tradetypes.LootBoxForTwoRequestSetsTrade;
import com.github.warrentode.todecoins.entity.villager.trades.tradetypes.MapForItemSetTrade;
import com.github.warrentode.todecoins.entity.villager.trades.tradetypes.OneSetForOneSetTrade;
import com.github.warrentode.todecoins.entity.villager.trades.tradetypes.OneSetForTwoSetsTrade;
import com.github.warrentode.todecoins.item.ModItems;
import com.github.warrentode.todecoins.loot.ModBuiltInLootTables;
import com.github.warrentode.todecoins.util.tags.ForgeTags;
import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableSet;
import it.unimi.dsi.fastutil.ints.Int2ObjectMap;
import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;
import net.minecraft.world.entity.npc.VillagerTrades;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.saveddata.maps.MapDecoration;

public class NumismatistTrades {
    static int rarityLevel1 = 1;
    static int rarityLevel2 = 2;

    private static ImmutableSet<ItemLike> RareOffers = ImmutableSet.of(
            Items.HEART_OF_THE_SEA.asItem().getDefaultInstance().getItem(),
            Items.ECHO_SHARD.asItem().getDefaultInstance().getItem(),
            Items.ENCHANTED_GOLDEN_APPLE.asItem().getDefaultInstance().getItem(),
            Items.MOJANG_BANNER_PATTERN.asItem().getDefaultInstance().getItem(),
            Items.TOTEM_OF_UNDYING.asItem().getDefaultInstance().getItem(),
            Items.DRAGON_BREATH.asItem().getDefaultInstance().getItem(),
            Items.ELYTRA.asItem().getDefaultInstance().getItem()
    );

    private static ImmutableSet<ItemLike> ContainerOffers = ImmutableSet.of(
            Items.BUNDLE.asItem().getDefaultInstance().getItem(),
            Items.SHULKER_BOX.asItem().getDefaultInstance().getItem(),
            Items.BLUE_SHULKER_BOX.asItem().getDefaultInstance().getItem(),
            Items.BLACK_SHULKER_BOX.asItem().getDefaultInstance().getItem(),
            Items.BROWN_SHULKER_BOX.asItem().getDefaultInstance().getItem(),
            Items.CYAN_SHULKER_BOX.asItem().getDefaultInstance().getItem(),
            Items.GRAY_SHULKER_BOX.asItem().getDefaultInstance().getItem(),
            Items.GREEN_SHULKER_BOX.asItem().getDefaultInstance().getItem(),
            Items.LIGHT_BLUE_SHULKER_BOX.asItem().getDefaultInstance().getItem(),
            Items.LIGHT_GRAY_SHULKER_BOX.asItem().getDefaultInstance().getItem(),
            Items.LIME_SHULKER_BOX.asItem().getDefaultInstance().getItem(),
            Items.MAGENTA_SHULKER_BOX.asItem().getDefaultInstance().getItem(),
            Items.ORANGE_SHULKER_BOX.asItem().getDefaultInstance().getItem(),
            Items.PINK_SHULKER_BOX.asItem().getDefaultInstance().getItem(),
            Items.PURPLE_SHULKER_BOX.asItem().getDefaultInstance().getItem(),
            Items.RED_SHULKER_BOX.asItem().getDefaultInstance().getItem(),
            Items.WHITE_SHULKER_BOX.asItem().getDefaultInstance().getItem(),
            Items.YELLOW_SHULKER_BOX.asItem().getDefaultInstance().getItem(),
            Items.ENDER_CHEST.asItem().getDefaultInstance().getItem());

    private static ImmutableSet<ItemLike> CoinList = ImmutableSet.of(
            // ANNIVERSARY COINS
            ModItems.LITTLE_BEAR_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.TUXEDO_CAT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.SCHOLAR_OWL_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.MARSHALL_NASH_CARNATION_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.MARSHALL_NASH_COSMOS_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.TREVOR_BRANNIGAN_CARNATION_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.TREVOR_BRANNIGAN_COSMOS_COIN.get().asItem().getDefaultInstance().getItem(),

            // BIRTHDAY COINS
            ModItems.BIRTHDAY_COIN_2023.get().asItem().getDefaultInstance().getItem(),

            // HALLOWEEN COINS
            ModItems.HALLOWEEN_COIN_2023.get().asItem().getDefaultInstance().getItem(),

            // CHRISTMAS COINS
            ModItems.CHRISTMAS_COIN_2023.get().asItem().getDefaultInstance().getItem(),

            // EASTER COINS
            ModItems.EASTER_COIN_2023.get().asItem().getDefaultInstance().getItem(),

            // SPRING COINS
            ModItems.COPPER_ALLAY_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_AXOLOTL_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_BAT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_BEE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_BLAZE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_CAMEL_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_CAT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_CAVE_SPIDER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_CHICKEN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_ENDERMAN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_HERO_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_OCELOT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_PIGLIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_COD_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_PUFFERFISH_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_SALMON_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_TROPICAL_FISH_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_COW_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_MOOSHROOM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_HORSE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_DONKEY_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_MULE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_SKELETON_HORSE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_ZOMBIE_HORSE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_FOX_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_FROG_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_GLOW_SQUID_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_SQUID_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_PARROT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_PIG_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_HOGLIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_RABBIT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_SHEEP_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_SNIFFER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_SNOW_GOLEM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_STRIDER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_TADPOLE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_TURTLE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_VILLAGER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_WANDERING_TRADER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_NUMISMATIST_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_DOLPHIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_GOAT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_IRON_GOLEM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_LLAMA_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_TRADER_LLAMA_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_PANDA_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_POLAR_BEAR_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_SPIDER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_WOLF_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_ZOMBIFIED_PIGLIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_CREEPER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_DROWNED_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_GUARDIAN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_ELDER_GUARDIAN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_ENDERMITE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_EVOKER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_GHAST_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_HUSK_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_MAGMA_CUBE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_SLIME_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_PHANTOM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_PIGLIN_BRUTE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_PILLAGER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_RAVAGER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_SHULKER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_SILVERFISH_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_SKELETON_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_STRAY_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_VEX_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_VINDICATOR_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_WARDEN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_WITCH_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_WITHER_SKELETON_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_WITHER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_ZOGLIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_ZOMBIE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_ZOMBIE_VILLAGER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_ENDER_DRAGON_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_ILLUSIONER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_GIANT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_MOOBLOOM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_COPPER_GOLEM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_GLARE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_ICEOLOGER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_MAULER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_WILDFIRE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_TUFF_GOLEM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_CRAB_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_SQUIRREL_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_PENGUIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_GUARD_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_RASCAL_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.COPPER_ARMADILLO_COIN.get().asItem().getDefaultInstance().getItem(),

            // SUMMER COINS
            ModItems.IRON_ALLAY_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_AXOLOTL_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_BAT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_BEE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_BLAZE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_CAMEL_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_CAT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_CAVE_SPIDER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_CHICKEN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_ENDERMAN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_HERO_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_OCELOT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_PIGLIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_COD_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_PUFFERFISH_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_SALMON_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_TROPICAL_FISH_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_COW_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_MOOSHROOM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_HORSE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_DONKEY_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_MULE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_SKELETON_HORSE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_ZOMBIE_HORSE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_FOX_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_FROG_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_GLOW_SQUID_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_SQUID_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_PARROT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_PIG_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_HOGLIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_RABBIT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_SHEEP_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_SNIFFER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_SNOW_GOLEM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_STRIDER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_TADPOLE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_TURTLE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_VILLAGER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_WANDERING_TRADER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_NUMISMATIST_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_DOLPHIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_GOAT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_IRON_GOLEM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_LLAMA_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_TRADER_LLAMA_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_PANDA_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_POLAR_BEAR_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_SPIDER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_WOLF_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_ZOMBIFIED_PIGLIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_CREEPER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_DROWNED_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_GUARDIAN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_ELDER_GUARDIAN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_ENDERMITE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_EVOKER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_GHAST_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_HUSK_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_MAGMA_CUBE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_SLIME_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_PHANTOM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_PIGLIN_BRUTE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_PILLAGER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_RAVAGER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_SHULKER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_SILVERFISH_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_SKELETON_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_STRAY_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_VEX_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_VINDICATOR_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_WARDEN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_WITCH_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_WITHER_SKELETON_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_WITHER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_ZOGLIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_ZOMBIE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_ZOMBIE_VILLAGER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_ENDER_DRAGON_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_ILLUSIONER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_GIANT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_MOOBLOOM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_COPPER_GOLEM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_GLARE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_ICEOLOGER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_MAULER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_WILDFIRE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_TUFF_GOLEM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_CRAB_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_SQUIRREL_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_PENGUIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_GUARD_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_RASCAL_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.IRON_ARMADILLO_COIN.get().asItem().getDefaultInstance().getItem(),

            // AUTUMN COINS
            ModItems.GOLD_ALLAY_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_AXOLOTL_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_BAT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_BEE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_BLAZE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_CAMEL_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_CAT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_CAVE_SPIDER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_CHICKEN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_ENDERMAN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_HERO_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_OCELOT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_PIGLIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_COD_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_PUFFERFISH_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_SALMON_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_TROPICAL_FISH_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_COW_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_MOOSHROOM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_HORSE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_DONKEY_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_MULE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_SKELETON_HORSE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_ZOMBIE_HORSE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_FOX_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_FROG_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_GLOW_SQUID_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_SQUID_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_PARROT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_PIG_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_HOGLIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_RABBIT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_SHEEP_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_SNIFFER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_SNOW_GOLEM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_STRIDER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_TADPOLE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_TURTLE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_VILLAGER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_WANDERING_TRADER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_NUMISMATIST_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_DOLPHIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_GOAT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_IRON_GOLEM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_LLAMA_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_TRADER_LLAMA_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_PANDA_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_POLAR_BEAR_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_SPIDER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_WOLF_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_ZOMBIFIED_PIGLIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_CREEPER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_DROWNED_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_GUARDIAN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_ELDER_GUARDIAN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_ENDERMITE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_EVOKER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_GHAST_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_HUSK_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_MAGMA_CUBE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_SLIME_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_PHANTOM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_PIGLIN_BRUTE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_PILLAGER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_RAVAGER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_SHULKER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_SILVERFISH_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_SKELETON_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_STRAY_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_VEX_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_VINDICATOR_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_WARDEN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_WITCH_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_WITHER_SKELETON_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_WITHER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_ZOGLIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_ZOMBIE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_ZOMBIE_VILLAGER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_ENDER_DRAGON_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_ILLUSIONER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_GIANT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_MOOBLOOM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_COPPER_GOLEM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_GLARE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_ICEOLOGER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_MAULER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_WILDFIRE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_TUFF_GOLEM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_CRAB_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_SQUIRREL_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_PENGUIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_GUARD_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_RASCAL_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.GOLD_ARMADILLO_COIN.get().asItem().getDefaultInstance().getItem(),

            // WINTER COINS
            ModItems.NETHERITE_ALLAY_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_AXOLOTL_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_BAT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_BEE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_BLAZE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_CAMEL_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_CAT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_CAVE_SPIDER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_CHICKEN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_ENDERMAN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_HERO_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_OCELOT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_PIGLIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_COD_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_PUFFERFISH_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_SALMON_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_TROPICAL_FISH_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_COW_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_MOOSHROOM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_HORSE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_DONKEY_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_MULE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_SKELETON_HORSE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_ZOMBIE_HORSE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_FOX_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_FROG_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_GLOW_SQUID_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_SQUID_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_PARROT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_PIG_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_HOGLIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_RABBIT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_SHEEP_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_SNIFFER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_SNOW_GOLEM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_STRIDER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_TADPOLE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_TURTLE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_VILLAGER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_WANDERING_TRADER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_NUMISMATIST_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_DOLPHIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_GOAT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_IRON_GOLEM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_LLAMA_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_TRADER_LLAMA_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_PANDA_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_POLAR_BEAR_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_SPIDER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_WOLF_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_ZOMBIFIED_PIGLIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_CREEPER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_DROWNED_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_GUARDIAN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_ELDER_GUARDIAN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_ENDERMITE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_EVOKER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_GHAST_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_HUSK_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_MAGMA_CUBE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_SLIME_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_PHANTOM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_PIGLIN_BRUTE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_PILLAGER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_RAVAGER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_SHULKER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_SILVERFISH_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_SKELETON_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_STRAY_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_VEX_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_VINDICATOR_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_WARDEN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_WITCH_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_WITHER_SKELETON_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_WITHER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_ZOGLIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_ZOMBIE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_ZOMBIE_VILLAGER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_ENDER_DRAGON_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_ILLUSIONER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_GIANT_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_MOOBLOOM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_COPPER_GOLEM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_GLARE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_ICEOLOGER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_MAULER_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_WILDFIRE_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_TUFF_GOLEM_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_CRAB_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_SQUIRREL_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_PENGUIN_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_GUARD_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_RASCAL_COIN.get().asItem().getDefaultInstance().getItem(),
            ModItems.NETHERITE_ARMADILLO_COIN.get().asItem().getDefaultInstance().getItem()
    );

    private static Int2ObjectMap<VillagerTrades.ItemListing[]> toIntMap(ImmutableMap<Integer, VillagerTrades.ItemListing[]> pMap) {
        return new Int2ObjectOpenHashMap<>(pMap);
    }

    public static Int2ObjectMap<VillagerTrades.ItemListing[]> NUMISMATIST_TRADES = makeTrades();

    private static Int2ObjectMap<VillagerTrades.ItemListing[]> makeTrades() {
        return NUMISMATIST_TRADES = toIntMap(
                ImmutableMap.of(
                        // 5 normal, season based trades
                        rarityLevel1, new VillagerTrades.ItemListing[]{
                                // a coin for a coin trade
                                new OneSetForOneSetTrade(
                                        CoinList, 1,
                                        CoinList, 1,
                                        OneSetForOneSetTrade.UNCOMMON_ITEMS_SUPPLY,
                                        OneSetForOneSetTrade.XP_LEVEL_1_SELL, 0),
                                // offer an off season coin for a current season coin
                                new OneSetForOneSetTrade(
                                        CoinList, 1,
                                        CoinList, 1,
                                        OneSetForOneSetTrade.UNCOMMON_ITEMS_SUPPLY,
                                        OneSetForOneSetTrade.XP_LEVEL_1_SELL, 0),
                                // offer a map for a coin
                                new MapForItemSetTrade(
                                        CoinList, 1,
                                        Items.COMPASS.getDefaultInstance(), 1,
                                        ForgeTags.StructureTags.ON_VILLAGE_EXPLORER_MAPS,
                                        "Merchant Map", MapDecoration.Type.MANSION,
                                        MapForItemSetTrade.UNCOMMON_ITEMS_SUPPLY,
                                        MapForItemSetTrade.XP_LEVEL_1_SELL,
                                        MapForItemSetTrade.HIGH_TIER_PRICE_MULTIPLIER
                                ),
                                // offer a container for 2 coins
                                new OneSetForTwoSetsTrade(
                                        ContainerOffers, 1,
                                        CoinList, 1,
                                        CoinList, 1,
                                        OneSetForTwoSetsTrade.UNCOMMON_ITEMS_SUPPLY,
                                        OneSetForTwoSetsTrade.XP_LEVEL_1_SELL, 0),
                                // offer a coin pack for 2 current season coins
                                new LootBoxForTwoRequestSetsTrade(
                                        Items.SHULKER_BOX.getDefaultInstance(),
                                        "tooltips.collectible_coin_pack",
                                        ModBuiltInLootTables.MYSTERY_COIN_PACK,
                                        CoinList, 1,
                                        CoinList, 1,
                                        LootBoxForTwoRequestSetsTrade.UNCOMMON_ITEMS_SUPPLY,
                                        LootBoxForTwoRequestSetsTrade.XP_LEVEL_1_SELL, 0)
                        },
                        // 1 rare, season based trade
                        rarityLevel2, new VillagerTrades.ItemListing[]{
                                // offer a Cagerium listing item for 2 current season coins
                                new OneSetForTwoSetsTrade(
                                        RareOffers, 1,
                                        CoinList, 1,
                                        CoinList, 1,
                                        OneSetForTwoSetsTrade.UNCOMMON_ITEMS_SUPPLY,
                                        OneSetForTwoSetsTrade.XP_LEVEL_1_SELL, 0),
                        }));
    }
}