package com.github.warrentode.todecoins.datagen.loot_tables.collectible_coins.trading;

import com.github.warrentode.todecoins.item.TCItems;
import com.github.warrentode.todecoins.loot.ModBuiltInLootTables;
import net.minecraft.data.loot.LootTableSubProvider;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.providers.number.ConstantValue;
import org.jetbrains.annotations.NotNull;

import java.util.function.BiConsumer;

import static com.github.warrentode.todecoins.datagen.LootTablesGen.COLLECTIBLE_COIN_CHANCE;

public class AutumnCoinLootGen implements LootTableSubProvider {
    @Override
    public void generate(@NotNull BiConsumer<ResourceLocation, LootTable.Builder> consumer) {
        consumer.accept(ModBuiltInLootTables.AUTUMN_COINS_LOOT,
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantValue.exactly(1.0F))
                                .setBonusRolls(ConstantValue.exactly(0F))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ALLAY_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ARMADILLO_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_AXOLOTL_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_BAT_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_BEE_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_BLAZE_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CAMEL_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CAT_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CAVE_SPIDER_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CHICKEN_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_COD_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_COPPER_GOLEM_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_COW_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CREEPER_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CRAB_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_DOLPHIN_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_DONKEY_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_DROWNED_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ELDER_GUARDIAN_GOLD.get())
                                        .when(COLLECTIBLE_COIN_CHANCE))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ENDER_DRAGON_GOLD.get())
                                        .when(COLLECTIBLE_COIN_CHANCE))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ENDERMAN_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ENDERMITE_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_EVOKER_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_FOX_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_FROG_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GHAST_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GIANT_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GLARE_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SQUID_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GLOW_SQUID_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GOAT_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GUARD_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GUARDIAN_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_HOGLIN_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_HORSE_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_HUSK_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ICEOLOGER_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ILLUSIONER_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_IRON_GOLEM_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_LLAMA_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_MAGMA_CUBE_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_MAULER_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_MOOBLOOM_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_MOOSHROOM_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_MULE_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_NUMISMATIST_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_OCELOT_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PARROT_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PANDA_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PHANTOM_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PENGUIN_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PILLAGER_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PIG_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PIGLIN_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PIGLIN_BRUTE_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PIGLIN_MERCHANT_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_POLAR_BEAR_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PUFFERFISH_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_RABBIT_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_RAVAGER_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_RASCAL_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SALMON_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SHEEP_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SHULKER_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SILVERFISH_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SKELETON_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SKELETON_HORSE_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SLIME_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SNIFFER_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SNOW_GOLEM_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SPIDER_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SQUIRREL_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_STRAY_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_TADPOLE_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_TROPICAL_FISH_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_TRADER_LLAMA_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_TURTLE_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_TUFF_GOLEM_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_VEX_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_VINDICATOR_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_VILLAGER_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WANDERING_TRADER_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WARDEN_GOLD.get())
                                        .when(COLLECTIBLE_COIN_CHANCE))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WILDFIRE_GOLD.get())
                                        .when(COLLECTIBLE_COIN_CHANCE))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WITHER_GOLD.get())
                                        .when(COLLECTIBLE_COIN_CHANCE))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WITHER_SKELETON_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WOLF_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WITCH_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ZOGLIN_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ZOMBIE_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ZOMBIE_HORSE_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ZOMBIE_VILLAGER_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ZOMBIFIED_PIGLIN_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CREAKING_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_HAPPY_GHAST_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_BREEZE_GOLD.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_BOGGED_GOLD.get()))
                        ));
    }
}