package com.github.warrentode.todecoins.datagen.loot_tables.collectible_coins.trading;

import com.github.warrentode.todecoins.item.TCItems;
import com.github.warrentode.todecoins.loot.ModBuiltInLootTables;
import net.minecraft.data.loot.LootTableSubProvider;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.providers.number.ConstantValue;
import org.jetbrains.annotations.NotNull;

import java.util.function.BiConsumer;

import static com.github.warrentode.todecoins.datagen.LootTablesGen.COLLECTIBLE_COIN_CHANCE;

public class SpringCoinLootGen implements LootTableSubProvider {
    @Override
    public void generate(@NotNull BiConsumer<ResourceLocation, LootTable.Builder> consumer) {
        consumer.accept(ModBuiltInLootTables.SPRING_COINS_LOOT,
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantValue.exactly(1.0F))
                                .setBonusRolls(ConstantValue.exactly(0F))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ELDER_GUARDIAN_COPPER.get())
                                        .when(COLLECTIBLE_COIN_CHANCE))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ENDER_DRAGON_COPPER.get())
                                        .when(COLLECTIBLE_COIN_CHANCE))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WITHER_COPPER.get())
                                        .when(COLLECTIBLE_COIN_CHANCE))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WILDFIRE_COPPER.get())
                                        .when(COLLECTIBLE_COIN_CHANCE))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WARDEN_COPPER.get())
                                        .when(COLLECTIBLE_COIN_CHANCE))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_BLAZE_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PIGLIN_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_HOGLIN_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ZOMBIFIED_PIGLIN_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GHAST_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_MAGMA_CUBE_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PIGLIN_BRUTE_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WITHER_SKELETON_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ENDERMITE_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SHULKER_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SKELETON_HORSE_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ZOMBIE_HORSE_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SKELETON_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ZOGLIN_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PIGLIN_MERCHANT_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ENDERMAN_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ALLAY_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_AXOLOTL_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_BAT_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_BEE_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CAMEL_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CAT_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CAVE_SPIDER_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CHICKEN_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_COD_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_COW_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_FOX_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_FROG_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_MOOBLOOM_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_MOOSHROOM_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_OCELOT_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PUFFERFISH_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SALMON_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_TROPICAL_FISH_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_HORSE_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_DONKEY_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_MULE_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SQUID_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GLOW_SQUID_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PARROT_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PIG_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_RABBIT_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SHEEP_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SNIFFER_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_NUMISMATIST_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WANDERING_TRADER_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_VILLAGER_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SNOW_GOLEM_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_TADPOLE_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_TURTLE_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_DOLPHIN_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GOAT_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_IRON_GOLEM_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_LLAMA_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_TRADER_LLAMA_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PANDA_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_POLAR_BEAR_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SPIDER_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WOLF_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CREEPER_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_DROWNED_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GUARDIAN_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_EVOKER_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_VINDICATOR_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_VEX_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_HUSK_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SLIME_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PHANTOM_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PILLAGER_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_RAVAGER_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SILVERFISH_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_STRAY_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WITCH_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ZOMBIE_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ZOMBIE_VILLAGER_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GIANT_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ILLUSIONER_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_COPPER_GOLEM_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_TUFF_GOLEM_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GLARE_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ICEOLOGER_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_MAULER_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CRAB_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SQUIRREL_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PENGUIN_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GUARD_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_RASCAL_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ARMADILLO_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CREAKING_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_HAPPY_GHAST_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_BREEZE_COPPER.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_BOGGED_COPPER.get()))
                        ));
    }
}