package com.github.warrentode.todecoins.datagen.loot_tables.collectible_coins.trading;

import com.github.warrentode.todecoins.item.TCItems;
import com.github.warrentode.todecoins.loot.ModBuiltInLootTables;
import net.minecraft.data.loot.LootTableSubProvider;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.providers.number.ConstantValue;
import org.jetbrains.annotations.NotNull;

import java.util.function.BiConsumer;

import static com.github.warrentode.todecoins.datagen.LootTablesGen.COLLECTIBLE_COIN_CHANCE;

public class SummerCoinLootGen implements LootTableSubProvider {
    @Override
    public void generate(@NotNull BiConsumer<ResourceLocation, LootTable.Builder> consumer) {
        consumer.accept(ModBuiltInLootTables.SUMMER_COINS_LOOT,
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantValue.exactly(1.0F))
                                .setBonusRolls(ConstantValue.exactly(0F))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ELDER_GUARDIAN_IRON.get())
                                        .when(COLLECTIBLE_COIN_CHANCE))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ENDER_DRAGON_IRON.get())
                                        .when(COLLECTIBLE_COIN_CHANCE))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WITHER_IRON.get())
                                        .when(COLLECTIBLE_COIN_CHANCE))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WILDFIRE_IRON.get())
                                        .when(COLLECTIBLE_COIN_CHANCE))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WARDEN_IRON.get())
                                        .when(COLLECTIBLE_COIN_CHANCE))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_BLAZE_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PIGLIN_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_HOGLIN_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ZOMBIFIED_PIGLIN_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GHAST_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_MAGMA_CUBE_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PIGLIN_BRUTE_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WITHER_SKELETON_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ENDERMITE_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SHULKER_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SKELETON_HORSE_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ZOMBIE_HORSE_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SKELETON_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ZOGLIN_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PIGLIN_MERCHANT_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ENDERMAN_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ALLAY_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_AXOLOTL_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_BAT_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_BEE_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CAMEL_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CAT_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CAVE_SPIDER_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CHICKEN_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_COD_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_COW_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_FOX_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_FROG_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_MOOBLOOM_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_MOOSHROOM_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_OCELOT_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PUFFERFISH_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SALMON_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_TROPICAL_FISH_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_HORSE_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_DONKEY_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_MULE_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SQUID_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GLOW_SQUID_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PARROT_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PIG_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_RABBIT_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SHEEP_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SNIFFER_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_NUMISMATIST_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WANDERING_TRADER_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_VILLAGER_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SNOW_GOLEM_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_TADPOLE_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_TURTLE_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_DOLPHIN_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GOAT_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_IRON_GOLEM_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_LLAMA_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_TRADER_LLAMA_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PANDA_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_POLAR_BEAR_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SPIDER_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WOLF_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CREEPER_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_DROWNED_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GUARDIAN_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_EVOKER_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_VINDICATOR_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_VEX_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_HUSK_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SLIME_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PHANTOM_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PILLAGER_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_RAVAGER_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SILVERFISH_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_STRAY_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WITCH_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ZOMBIE_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ZOMBIE_VILLAGER_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GIANT_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ILLUSIONER_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_COPPER_GOLEM_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_TUFF_GOLEM_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GLARE_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ICEOLOGER_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_MAULER_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CRAB_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SQUIRREL_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PENGUIN_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GUARD_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_RASCAL_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ARMADILLO_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CREAKING_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_HAPPY_GHAST_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_BREEZE_IRON.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_BOGGED_IRON.get()))
                        ));
    }
}