package com.github.warrentode.todecoins.datagen.loot_tables.collectible_coins.trading;

import com.github.warrentode.todecoins.item.TCItems;
import com.github.warrentode.todecoins.loot.ModBuiltInLootTables;
import net.minecraft.data.loot.LootTableSubProvider;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.providers.number.ConstantValue;
import org.jetbrains.annotations.NotNull;

import java.util.function.BiConsumer;

import static com.github.warrentode.todecoins.datagen.LootTablesGen.COLLECTIBLE_COIN_CHANCE;

public class WinterCoinLootGen implements LootTableSubProvider {
    @Override
    public void generate(@NotNull BiConsumer<ResourceLocation, LootTable.Builder> consumer) {
        consumer.accept(ModBuiltInLootTables.WINTER_COINS_LOOT,
                LootTable.lootTable()
                        .withPool(LootPool.lootPool()
                                .setRolls(ConstantValue.exactly(1.0F))
                                .setBonusRolls(ConstantValue.exactly(0F))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ELDER_GUARDIAN_NETHERITE.get())
                                        .when(COLLECTIBLE_COIN_CHANCE))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ENDER_DRAGON_NETHERITE.get())
                                        .when(COLLECTIBLE_COIN_CHANCE))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WITHER_NETHERITE.get())
                                        .when(COLLECTIBLE_COIN_CHANCE))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WILDFIRE_NETHERITE.get())
                                        .when(COLLECTIBLE_COIN_CHANCE))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WARDEN_NETHERITE.get())
                                        .when(COLLECTIBLE_COIN_CHANCE))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_BLAZE_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PIGLIN_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_HOGLIN_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ZOMBIFIED_PIGLIN_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GHAST_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_MAGMA_CUBE_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PIGLIN_BRUTE_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WITHER_SKELETON_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ENDERMITE_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SHULKER_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SKELETON_HORSE_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ZOMBIE_HORSE_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SKELETON_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ZOGLIN_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PIGLIN_MERCHANT_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ENDERMAN_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ALLAY_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_AXOLOTL_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_BAT_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_BEE_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CAMEL_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CAT_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CAVE_SPIDER_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CHICKEN_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_COD_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_COW_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_FOX_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_FROG_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_MOOBLOOM_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_MOOSHROOM_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_OCELOT_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PUFFERFISH_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SALMON_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_TROPICAL_FISH_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_HORSE_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_DONKEY_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_MULE_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SQUID_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GLOW_SQUID_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PARROT_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PIG_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_RABBIT_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SHEEP_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SNIFFER_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_NUMISMATIST_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WANDERING_TRADER_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_VILLAGER_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SNOW_GOLEM_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_TADPOLE_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_TURTLE_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_DOLPHIN_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GOAT_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_IRON_GOLEM_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_LLAMA_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_TRADER_LLAMA_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PANDA_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_POLAR_BEAR_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SPIDER_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WOLF_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CREEPER_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_DROWNED_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GUARDIAN_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_EVOKER_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_VINDICATOR_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_VEX_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_HUSK_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SLIME_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PHANTOM_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PILLAGER_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_RAVAGER_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SILVERFISH_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_STRAY_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_WITCH_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ZOMBIE_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ZOMBIE_VILLAGER_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GIANT_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ILLUSIONER_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_COPPER_GOLEM_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_TUFF_GOLEM_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GLARE_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ICEOLOGER_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_MAULER_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CRAB_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_SQUIRREL_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_PENGUIN_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_GUARD_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_RASCAL_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_ARMADILLO_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_CREAKING_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_HAPPY_GHAST_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_BREEZE_NETHERITE.get()))
                                .add(LootItem.lootTableItem(TCItems.COLLECTIBLE_COIN_BOGGED_NETHERITE.get()))
                        ));
    }
}