name: CI & Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]   # publish only when you make a GitHub release
  workflow_dispatch:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Unit tests
        run: ./gradlew test --stacktrace
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

  publish:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'release'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}