name: Publish

on: [ pull_request, workflow_dispatch ]

env:
  MINECRAFT_VERSION: 1.19.2
  JAVA_VERSION: 17
  VERSION: 1.19.2-1.5.1
  RELEASE_NAME: TodeCoins 1.19.2-1.5.1
  GITHUB_TOKEN: ${{ secrets.TODECOINS_KEY }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Print ChangeLog
        uses: git log --pretty="- %s" > CHANGELOG.md

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build
        run: ./gradlew clean build

      - name: mc-publish
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          github-tag: "v${{env.VERSION}}"
          github-token: "${{env.TODECOINS_KEY}}"

          owner: "warrentode"
          group: "com.github.warrentode"
          name: "${{env.RELEASE_NAME}}"
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: forge
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"